### PR TITLE
Update whats-new-visual-studio-2019.md

### PR DESCRIPTION
**Pull request by hellotaotao**
The old translation means "how to design the new Visual Studio start window"

### CODE REVIEW

**Comment by srvbpigh** [comment]
你好，@hellotaotao：

感谢你的发布内容！ 我们正在处理你的建议，将很快更新。  


顺祝商祺！ 

Microsoft DOCS 全球化体验团队

**Comment by srvbpigh** [comment]
你好，@hellotaotao:

感谢你的发布内容！很遗憾，你的反馈未被采纳。可在下方找到有关未采纳的建议的注释：

----------------------------º---------------------------- 
 **docs/ide/whats-new-visual-studio-2019.md** 

**当前版本:** 
```
有关详细信息，请参阅博客文章 [Get to code:How we designed the new Visual Studio start window](https://devblogs.microsoft.com/visualstudio/get-to-code-how-we-designed-the-new-visual-studio-start-window/)（开始编码：如何设计新的 Visual Studio 开始窗口）。
```

**请求的更改:** 
```
有关详细信息，请参阅博客文章 [Get to code:How we designed the new Visual Studio start window](https://devblogs.microsoft.com/visualstudio/get-to-code-how-we-designed-the-new-visual-studio-start-window/)（开始编码：我们是如何设计了新的 Visual Studio 开始窗口）。
```
**未采纳原因:** Suggested Translation is overtranslated.
----------------------------º---------------------------- 



非常感谢你为我们的文章贡献内容，期待收到你的宝贵意见。感谢你抽出宝贵时间参与和支持。

Microsoft DOCS 全球体验团队

**Comment by hellotaotao** [comment]
The original translation is very very misleading and my version is absolutely not overtranslated. 

Don't you feel the difference of "How to design ..." and "How we designed ..."?
The first one is a tutorial while the latter is a record. 
In the case of this article, it is basically only a change log, rather than teaching people about designing a "Visual Studio start window".

Please look at the difference again and I believe you will agree with me.

**Comment by imba-tjd** [comment]
You need to change the original English article if you think there is a necessity. 翻译要忠于原文

**Pull request closed without merging**
